### ISSUE TITLE
[Refactor] delete warn log

### ISSUE THREAD

**Issue by shinb-bong** [2023Summer/mr-playlist-backend#49]
## Description
yml 프로필 분리와 warn 로그 제거
기능 추가 및 파일 추가

### To-do

- [ ] 프로필 공통부분과 따로 관리 분리
- [ ] 레디스 0.0.0.0 포트 테스트 사용
- [ ] springboot 3.0.2 컨트롤러 warn 로그 없애기 
https://www.inflearn.com/chats/788304/spring-boot-3-0-2%EB%A5%BC-%EC%82%AC%EC%9A%A9-%EC%A4%91%EC%9D%B4%EC%8B%A0-%EB%B6%84%EB%93%A4%EC%9D%B4-%EC%84%A4%EC%A0%95%ED%95%98%EB%A9%B4-%EC%A2%8B%EC%9D%80-%EA%B2%83

/* 브랜치 생성시 feature/#{이슈번호} 형식 작성 */
