### ISSUE TITLE
[Feat] save image

### ISSUE THREAD

**Issue by shinb-bong** [2023Summer/mr-playlist-backend#52]
## Description
이미지 저장 기능이 필요할 듯 합니다.
위치는 플레이리스트, 가수, 멤버 정도 있을 듯 합니다.
기능 추가 및 파일 추가

### To-do

- [ ] 플레이리스트 이미지 추가(만약 이미지가 없을 경우 첫곡의 썸네일 url)
- [ ] 가수 이미지 추가(이미지가 없을 경우 디폴트 이미지)
- [ ] 멤버 이미지 추가(이미지가 없을 경우 디폴트 이미지)

/* 브랜치 생성시 feature/#{이슈번호} 형식 작성 */
