### ISSUE TITLE
[Feature] save image ver.2

### ISSUE THREAD

**Issue by ShsH0920** [2023Summer/mr-playlist-backend#65]
## Description

S3를 사용한 image save기능을 작성합니다.
(이전 브랜치를 오래 살려둔 탓에 충돌되는것이 많아 새로 브랜치를 만들었습니다.)

### To-do

- [x] S3 관련 기초 설정 파일 작성
- [x] 플레이리스트 이미지 추가(만약 이미지가 없을 경우 첫곡의 썸네일 url)
- [ ] 음악 이미지 추출 메소드 + youtube가 아닐경우 디폴트 이미지
- [x] 가수 이미지 추가(이미지가 없을 경우 디폴트 이미지)

/* 브랜치 생성시 feature/#{이슈번호} 형식 작성 */
