### ISSUE TITLE
[Feature] DB 설정 정보 및 p6spy 의존성

### ISSUE THREAD

**Issue by shinb-bong** [2023Summer/mr-playlist-backend#7]
## Description
DB 설정과 p6spy 의존성 주입을 합니다.
### To-do
 - [x] DB 정보 설정
 - [x] p6spy 의존성 주입
 - [x] 포맷팅
 - [x] logback.xml 설정

/* 브랜치 생성시 feature/#{이슈번호} 형식 작성 */
